server:
  port: 8980
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RudraMazumder/config-server.git
          username: RudraMazumder
          password: Database-1
          searchPaths: norad*
          cloneOnStart: true
          
          repos: 
            norad: 
              pattern: '*/norad'
              uri: https://github.com/RudraMazumder/config-server.git
              username: RudraMazumder
              password: Database-1
              searchPaths: norad*
              cloneOnStart: true
            bth: 
              pattern: '*/bth'
              uri: https://github.com/RudraMazumder/config-server.git
              username: RudraMazumder
              password: Database-1
              searchPaths: bth*
              cloneOnStart: true  
            badtarget: 
              pattern: '*/badtarget'
              uri: https://github.com/RudraMazumder/config-server.git
              username: RudraMazumder
              password: Database-1
              searchPaths: badtarget*
              cloneOnStart: true    
            
             
                
          