server:
  port: 8980
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RudraMazumder/config-server.git
          username: RudraMazumder
          password: Database-1
          searchPaths: "{application},{label}"
          cloneOnStart: true
          